[pytest] 
log_cli = true
log_cli_level = INFO

minversion = 7.0 
addopts = -v -n 1 
testpaths = tests 

markers = 
    smoke: quick sanity tests 
    regression: full regression suite 
    uitest: login related tests 
    jsondatadriventesting: data driven testing using json file 